---
# OpenVPN Download variables
# --------------------------
openvpn_mirror_location:  "{{ streisand_mirror_location }}/openvpn"
openvpn_mirror_href_base: "/mirror/openvpn"

openvpn_base_download_url: "https://build.openvpn.net/downloads/releases/latest"

openvpn_source_filename:      "openvpn-latest-stable.tar.gz"
openvpn_source_sig_filename:  "{{ openvpn_source_filename }}.asc"
openvpn_source_href:          "{{ openvpn_mirror_href_base }}/{{ openvpn_source_filename }}"
openvpn_source_sig_href:      "{{ openvpn_mirror_href_base }}/{{ openvpn_source_sig_filename }}"

openvpn_windows_installer_filename:     "openvpn-install-latest-stable.exe"
openvpn_windows_installer_sig_filename: "{{ openvpn_windows_installer_filename }}.asc"
openvpn_windows_installer_href:         "{{ openvpn_mirror_href_base }}/{{ openvpn_windows_installer_filename }}"
openvpn_windows_installer_sig_href:     "{{ openvpn_mirror_href_base }}/{{ openvpn_windows_installer_sig_filename }}"

openvpn_gpg_keyid: "5ACFEAC6"
openvpn_download_files:
  - { "file": "{{ openvpn_source_filename }}", "sig": "{{ openvpn_source_sig_filename }}" }
  - { "file": "{{ openvpn_windows_installer_filename }}", "sig": "{{ openvpn_windows_installer_sig_filename }}" }

# macOS
tunnelblick_version:  "3.7.6a"
tunnelblick_build:    "5080"
tunnelblick_filename: "Tunnelblick_{{ tunnelblick_version }}_build_{{ tunnelblick_build }}.dmg"
tunnelblick_href:     "{{ openvpn_mirror_href_base }}/{{ tunnelblick_filename }}"
tunnelblick_url:      "https://tunnelblick.net/release/{{ tunnelblick_filename }}"
tunnelblick_checksum: "sha256:42b50bd09296f98e55bdf4262a33d42067d1922157b010a02976cc74f514b677"
