---
# Stunnel Download variables
# --------------------------
stunnel_mirror_location: "{{ streisand_mirror_location }}/stunnel"

stunnel_michal_trojnara_key_id: "0xFCD53E9D74C732D1"
stunnel_michal_trojnara_expected_fingerprint: "F6B1 BFC5 5F32 243F B2C8  919A FCD5 3E9D 74C7 32D1"

stunnel_version: "5.02"
stunnel_base_download_url: "http://www.stunnel.org/downloads"

stunnel_installer_filename: "stunnel-{{ stunnel_version }}-installer.exe"
stunnel_installer_url: "{{ stunnel_base_download_url }}/{{ stunnel_installer_filename }}"
stunnel_installer_sig_url: "{{ stunnel_installer_url }}.asc"

stunnel_source_filename: "stunnel-{{ stunnel_version }}.tar.gz"
stunnel_source_url: "{{ stunnel_base_download_url }}/{{ stunnel_source_filename }}"
stunnel_source_sig_url: "{{ stunnel_source_url }}.asc"

stunnel_download_urls:
  - "{{ stunnel_installer_url }}"
  - "{{ stunnel_installer_sig_url }}"
  - "{{ stunnel_source_url }}"
  - "{{ stunnel_source_sig_url }}"
