---
dist: trusty
language: python
cache: pip
python: "2.7"

# Use isolated build instance
sudo: required

env:
  global:
    - ANSIBLE_CONFIG=tests/ansible.cfg
  matrix:
    - RUN="shellcheck yamlcheck syntax ci" SITE="global_vars/default-site.yml"
    - RUN="ci" SITE="tests/site_vars/openconnect.yml"
    - RUN="ci" SITE="tests/site_vars/openvpn.yml"
    - RUN="ci" SITE="tests/site_vars/shadowsocks.yml"
    - RUN="ci" SITE="tests/site_vars/ssh.yml"
    - RUN="ci" SITE="tests/site_vars/cloudflared.yml"
    - RUN="ci" SITE="random"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-pip python-dev ca-certificates shellcheck -qq
  # workaround for https://travis-ci.community/t/then-sudo-apt-get-update-failed-public-key-is-not-available-no-pubkey-6b05f25d762e3157-in-ubuntu-xenial/1728
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157

install:
  - pip install ansible==2.8.0
  - pip install urllib3 yamllint
  - ansible --version

script:
  - ./tests/tests.sh
