---
dist: trusty
language: python
python: "2.7"

group: edge

# Use isolated GCE instance
sudo: required

env:
  global:
    - ANSIBLE_CONFIG=tests/ansible.cfg

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-pip python-dev ca-certificates shellcheck -qq

install:
  - pip install ansible==2.3.1.0
  - pip install urllib3
  - ansible --version

script:
  # Run shellcheck lint on streisand script
  - shellcheck ./streisand
  # Run syntax checks on playbooks and roles
  - ./tests/tests.sh syntax
  # Install additional packages, configure lxc, start streisand container
  # Run entire playbook against lxc container
  - ./tests/tests.sh ci
