---
streisand_common_packages:
  # Ensure that Apparmor is installed
  - apparmor
  # Enables support for the HTTPS protocol in APT sources
  - apt-transport-https
  # Used to compile Libreswan and OpenConnect Server (ocserv)
  - build-essential
  # Used to perform API requests, including the version check for
  # the Tor Browser Bundle
  - curl
  # Enables automation of programs and scripts that ask for user input
  - expect
  # Used to verify GPG signatures for mirrored packages
  - gnupg
  # Used to configure firewall rules
  - iptables
  # Used for documentation generation
  - markdown
  # Ensures the server's clock is set properly
  - ntp
  # Required to use the Ansible `expect` module
  - python-pexpect
  # Required for the apt_repository module
  - python-software-properties
  # Used to generate convenient QR codes for mobile clients in the
  # Shadowsocks and Tor roles
  - qrencode
  # Used for automatically installing security updates
  - unattended-upgrades
  # Word List dictionary used by several roles to generate random
  # (yet typeable!) passphrases
  - wamerican-huge

streisand_gateway_location: "/var/www/streisand"

streisand_local_directory: "generated-docs"

streisand_header_template: "/tmp/header.html"
streisand_footer_template: "/tmp/footer.html"
