---
streisand_common_packages:
  # Used to perform API requests, including the version check for
  # the Tor Browser Bundle
  - curl
  # Used to verify GPG signatures for mirrored packages
  - gnupg
  # Used for documentation generation
  - markdown
  # Ensures the server's clock is set properly
  - openntpd
  # Required for the apt_repository module
  - python-software-properties
  # Used to generate convenient QR codes for mobile clients in the
  # Shadowsocks and Tor roles
  - qrencode
  # Word List dictionary used by several roles to generate random
  # (yet typeable!) passphrases
  - wamerican-huge
  # Used for automatically installing security updates
  - unattended-upgrades

streisand_gateway_location: "/var/www/streisand"

streisand_local_directory: "../generated-docs"

streisand_header_template: "/tmp/header.html"
streisand_footer_template: "/tmp/footer.html"
