---

- name: Add the WireGuard PPA
  apt_repository:
    repo: 'ppa:wireguard/wireguard'
  register: wireguard_add_apt_repository
  until: not wireguard_add_apt_repository.failed
  retries: "{{ apt_repository_retries }}"
  delay: "{{ apt_repository_delay }}"

- name: Install the WireGuard packages
  apt:
    package:
      - wireguard
