---
- name: Make the directory where mirrored files will be stored
  file:
    path: "{{ streisand_mirror_location }}"
    owner: www-data
    group: www-data
    mode: 0755
    state: directory

# Download and verify client files
- include: openconnect.yml
- include: openvpn.yml
- include: shadowsocks.yml
- include: ssh.yml
- include: stunnel.yml
- include: tor.yml

- name: Generate the Markdown mirror page
  template:
    src: mirror-index{{ item.value.file_suffix }}.md.j2
    dest: "{{ streisand_mirror_location }}/index{{ item.value.file_suffix }}.md"
  with_dict: "{{ streisand_languages }}"

- name: Convert the Markdown mirror page into HTML
  shell: markdown {{ streisand_mirror_location }}/index{{ item.value.file_suffix }}.md | cat {{ streisand_i18n_header_template }} - {{ streisand_footer_template }} > {{ streisand_mirror_location }}/index{{ item.value.file_suffix }}.html
  with_dict: "{{ streisand_languages }}"
