---
- name: Include the SSH mirror variables
  include_vars: ssh.yml

- name: Make the directory where the SSH client mirrored files will be stored
  file:
    path: "{{ ssh_mirror_location }}"
    owner: www-data
    group: www-data
    mode: 0755
    state: directory

- block:
    - name: Mirror sshuttle
      get_url:
        url: "{{ sshuttle_url }}"
        dest: "{{ ssh_mirror_location }}/{{ sshuttle_filename }}"
        checksum: "{{ sshuttle_checksum }}"
        owner: www-data
        group: www-data
        mode: 0644

    - include: download-and-verify.yml
      vars:
        project_name: "PuTTY"
        project_signer: "PuTTY Releases"
        project_signing_key: "{{ putty_key_id }}"
        project_expected_fingerprint: "{{ putty_expected_fingerprint }}"
        project_mirror_location: "{{ ssh_mirror_location }}"
        project_download_urls: "{{ putty_download_urls }}"
        signature_extension: "gpg"
  rescue:
    - name: "{{ streisand_mirror_warning }}"
      pause:
        seconds: "{{ streisand_mirror_warning_seconds }}"
