---
- name: Include the stunnel mirror variables
  include_vars: stunnel.yml

- name: Make the directory where the stunnel mirrored files will be stored
  file:
    path: "{{ stunnel_mirror_location }}"
    owner: www-data
    group: www-data
    mode: 0755
    state: directory

- block:
    - include: download-and-verify.yml
      vars:
        project_name: "stunnel"
        project_signer: "Michal Trojnara"
        project_signing_key: "{{ stunnel_michal_trojnara_key_id }}"
        project_expected_fingerprint: "{{ stunnel_michal_trojnara_expected_fingerprint }}"
        project_mirror_location: "{{ stunnel_mirror_location }}"
        project_download_urls: "{{ stunnel_download_urls }}"
  rescue:
    - name: "{{ streisand_mirror_warning }}"
      pause:
        seconds: "{{ streisand_mirror_warning_seconds }}"

- name: Get the current stunnel version from the downloaded source file
  shell: ls *.tar.gz | tail -n 1 | sed -e 's/stunnel-\(.*\)\.tar\.gz/\1/'
  args:
    chdir: "{{ stunnel_mirror_location }}"
  register: stunnel_latest_check

- name: Set the target stunnel version
  set_fact:
    stunnel_version: "{{ stunnel_latest_check.stdout }}"
