---
- name: Ensure that the Apache web server is not installed in order to avoid conflicts with Nginx
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apache_packages_to_remove }}"

- name: "Add the official Nginx APT key; hiding 25 lines of log..."
  apt_key:
    id: 7BD9BF62
    data: "{{ item }}"
  with_file: nginx_signing.key
  no_log: True

- name: Add the official Nginx repository
  apt_repository:
    repo: "deb https://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_lsb.codename }} nginx"

- name: Install Nginx
  apt:
    name: nginx

- name: Update Nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Set up Nginx vhost directories
  file:
    path: /etc/nginx/{{ item }}
    state: directory
  with_items:
    - sites-available
    - sites-enabled

- name: Create the nginx systemd configuration directory
  file:
    path: "{{ nginx_systemd_service_path }}"
    state: directory

- name: Generate the nginx systemd service file
  template:
    src: nginx.service.j2
    dest: "{{ nginx_systemd_service_path }}/10-restart-failure.conf"
    mode: 0644

- name: Enable the nginx service
  systemd:
    daemon_reload: yes
    name: nginx.service
    enabled: yes
    state: restarted
