---
streisand_gateway_url: "https://{{ streisand_ipv4_address }}"

streisand_gateway_htpasswd_file: "/etc/nginx/htpasswd"
streisand_gateway_password_file: "/etc/nginx/gateway-password.txt"

streisand_gateway_markdown_firewall_information: "/tmp/{{ streisand_server_name }}-firewall-information.md"
streisand_gateway_html_firewall_information: "/tmp/{{ streisand_server_name }}-firewall-information.html"

streisand_gateway_markdown_instructions: "/tmp/{{ streisand_server_name }}.md"
streisand_gateway_html_instructions: "/tmp/{{ streisand_server_name }}.html"

streisand_gateway_markdown_index: "{{ streisand_gateway_location }}/index.md"
streisand_gateway_html_index: "{{ streisand_gateway_location }}/index.html"


openssl_ca_base: "/root/ca"
openssl_ca_private_dir: "{{ openssl_ca_base }}/private"
openssl_ca_newcerts_dir: "{{ openssl_ca_base }}/newcerts"
openssl_ca_key: "{{ openssl_ca_private_dir }}/cakey.pem"
openssl_ca_certificate: "{{ openssl_ca_base }}/cacert.pem"


nginx_days_valid: "1825"

nginx_self_signed_certificate: "/etc/ssl/certs/{{ streisand_server_name }}.crt"
nginx_self_signed_certificate_request: "/etc/ssl/certs/{{ streisand_server_name }}.csr"
nginx_private_key: "/etc/ssl/private/{{ streisand_server_name }}.key"

nginx_internal_hidden_service_address: "127.0.0.1:8181"
