---
- name: Include the stunnel mirror variables
  include_vars: mirror.yml

- name: Make the directory where the stunnel mirrored files will be stored
  file:
    path: "{{ stunnel_mirror_location }}"
    owner: www-data
    group: www-data
    mode: 0755
    state: directory

- block:
    - include_role:
        name: download-and-verify
      vars:
        project_name: "stunnel"
        project_signer: "Michal Trojnara"
        project_signing_key: "{{ stunnel_michal_trojnara_key_id }}"
        project_expected_fingerprint: "{{ stunnel_michal_trojnara_expected_fingerprint }}"
        project_download_location: "{{ stunnel_mirror_location }}"
        project_download_urls: "{{ stunnel_download_urls }}"
  rescue:
    - name: "{{ streisand_mirror_warning }}"
      pause:
        seconds: "{{ streisand_mirror_warning_seconds }}"

- name: Get the current stunnel version from the downloaded source file
  shell: ls *.tar.gz | tail -n 1 | sed -e 's/stunnel-\(.*\)\.tar\.gz/\1/'
  args:
    chdir: "{{ stunnel_mirror_location }}"
  register: stunnel_latest_check
  changed_when: False

- name: Set the target stunnel version
  set_fact:
    stunnel_version: "{{ stunnel_latest_check.stdout }}"

- name: Generate the stunnel Markdown mirror page
  template:
    src: mirror{{ item.value.file_suffix }}.md.j2
    dest: "{{ stunnel_mirror_location }}/index{{ item.value.file_suffix }}.md"
  with_dict: "{{ streisand_languages }}"

- name: Convert the stunnel Markdown mirror page into HTML
  shell: markdown {{ stunnel_mirror_location }}/index{{ item.value.file_suffix }}.md | cat {{ streisand_i18n_header_template }} - {{ streisand_footer_template }} > {{ stunnel_mirror_location }}/index{{ item.value.file_suffix }}.html
  with_dict: "{{ streisand_languages }}"
