---
- name: Set the DigitalOcean Access Token fact to the value that was entered, or attempt to retrieve it from the environment if the entry is blank
  set_fact:
    do_access_token: "{{ do_access_token_entry | default( lookup('env', 'DIGITALOCEAN_API_KEY') ) }}"

- name: Get the default SSH key
  command: cat ~/.ssh/id_rsa.pub
  register: ssh_key

- block:
    - name: Add the SSH key to DigitalOcean if it doesn't already exist
      digital_ocean:
        command: ssh
        name: "{{ do_ssh_name }}"
        ssh_pub_key: "{{ ssh_key.stdout }}"
        api_token: "{{ do_access_token }}"
      register: do_ssh_key
  rescue:
    - fail:
        msg: "* The API Access Token might be incorrect or missing the Write Scope. OR * The SSH key may already exist in the DigitalOcean Control Panel under a different name. OR * The dopy Python module might not be installed. Use `pip install dopy==0.3.5` to install this module. On the latest version of OS X, dopy > 0.3.5 is currently broken."

- block:
  - name: Create the new Droplet
    digital_ocean:
      command: droplet
      name: "{{ do_server_name }}"
      ssh_key_ids: "{{ do_ssh_key.ssh_key.id }}"
      size_id: "{{ do_small_droplet_size_id }}"
      region_id: "{{ regions[do_region] }}"
      image_id: "{{ do_ubuntu_x64_image_id }}"
      unique_name: yes
      wait: yes
      api_token: "{{ do_access_token }}"
    register: streisand_server
  rescue:
    - fail:
        msg: "Unable to create the Droplet. Please ensure that the API Access Token you provided has the Write Scope enabled."

- name: Wait until the server has finished booting and OpenSSH is accepting connections
  wait_for:
    host: "{{ streisand_server.droplet.ip_address }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600

- name: Create the in-memory inventory group
  add_host:
    name: "{{ streisand_server.droplet.ip_address }}"
    groups: streisand-host

- name: Set the streisand_ipv4_address variable
  set_fact:
    streisand_ipv4_address: "{{ streisand_server.droplet.ip_address }}"

- name: Set the streisand_server_name variable
  set_fact:
    streisand_server_name: "{{ do_server_name }}"
