---
- name: Get the default SSH key
  command: cat ~/.ssh/id_rsa.pub
  register: ssh_key

- name: Add the SSH key to DigitalOcean if it doesn't already exist
  digital_ocean_sshkey: name="{{ do_ssh_name }}"
                        ssh_pub_key="{{ ssh_key.stdout }}"
                        client_id="{{ do_client_id }}"
                        api_key="{{ do_api_key }}"
  register: do_ssh_key

- name: Get the latest 'Ubuntu 14.04 x64' image ID from the DigitalOcean API
  shell: curl -s 'https://api.digitalocean.com/images/?client_id={{ do_client_id }}&api_key={{ do_api_key }}' | {{ ansible_python_interpreter }} -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [img for img in j["images"] if img["slug"]=="ubuntu-14-04-x64"][0]["id"]'
  register: do_ubuntu_x64_image_id

- name: Create the server. If this task fails with an "invalid region" error, then DigitalOcean is temporarily not allowing new 512MB Droplets to be provisioned in the selected region. You can either try the same region again later, or choose a different location.
  digital_ocean: command=droplet
                 name={{ do_server_name }}
                 ssh_key_ids={{ do_ssh_key.ssh_key.id }}
                 client_id="{{ do_client_id }}"
                 api_key="{{ do_api_key }}"
                 size_id={{ do_small_droplet_size_id }}
                 region_id={{ regions[do_region] }}
                 image_id={{ do_ubuntu_x64_image_id.stdout }}
                 unique_name=yes
  register: streisand_server

- name: Wait until the server has finished booting and OpenSSH is accepting connections
  wait_for: host={{ streisand_server.droplet.ip_address }}
            port=22
            search_regex=OpenSSH
            timeout=300

- name: Create the in-memory inventory group
  add_host: name={{ streisand_server.droplet.ip_address }}
            groups=streisand-host

- name: Set the streisand_ipv4_address variable
  set_fact: streisand_ipv4_address="{{ streisand_server.droplet.ip_address }}"

- name: Set the streisand_server_name variable
  set_fact: streisand_server_name="{{ do_server_name }}"
