---
# OpenVPN Download variables
# --------------------------
openvpn_mirror_location: "{{ streisand_mirror_location }}/openvpn"
openvpn_mirror_href_base: "/mirror/openvpn"

openvpn_samuli_seppanen_key_id: "0xC29D97ED198D22A3"
openvpn_samuli_seppanen_expected_fingerprint: "Key fingerprint = 0330 0E11 FED1 6F59 715F  9996 C29D 97ED 198D 22A3"

openvpn_version: "2.3.12"
openvpn_base_download_url: "http://swupdate.openvpn.org/community/releases"

openvpn_source_filename: "openvpn-{{ openvpn_version }}.tar.gz"
openvpn_source_sig_filename: "{{ openvpn_source_filename }}.asc"
openvpn_source_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_source_filename }}"
openvpn_source_sig_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_source_sig_filename }}"
openvpn_source_url: "{{ openvpn_base_download_url }}/{{ openvpn_source_filename }}"
openvpn_source_sig_url: "{{ openvpn_base_download_url }}/{{ openvpn_source_sig_filename }}"

openvpn_windows32_installer_filename: "openvpn-install-{{ openvpn_version }}-I001-i686.exe"
openvpn_windows32_installer_sig_filename: "{{ openvpn_windows32_installer_filename }}.asc"
openvpn_windows32_installer_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_windows32_installer_filename }}"
openvpn_windows32_installer_sig_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_windows32_installer_sig_filename }}"
openvpn_windows32_installer_url: "{{ openvpn_base_download_url }}/{{ openvpn_windows32_installer_filename }}"
openvpn_windows32_installer_sig_url: "{{ openvpn_base_download_url }}/{{ openvpn_windows32_installer_sig_filename }}"

openvpn_windows64_installer_filename: "openvpn-install-{{ openvpn_version }}-I601-x86_64.exe"
openvpn_windows64_installer_sig_filename: "{{ openvpn_windows64_installer_filename }}.asc"
openvpn_windows64_installer_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_windows64_installer_filename }}"
openvpn_windows64_installer_sig_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_windows64_installer_sig_filename }}"
openvpn_windows64_installer_url: "{{ openvpn_base_download_url }}/{{ openvpn_windows64_installer_filename }}"
openvpn_windows64_installer_sig_url: "{{ openvpn_base_download_url }}/{{ openvpn_windows64_installer_sig_filename }}"

openvpn_download_urls:
  - "{{ openvpn_source_url }}"
  - "{{ openvpn_source_sig_url }}"
  - "{{ openvpn_windows32_installer_url }}"
  - "{{ openvpn_windows32_installer_sig_url }}"
  - "{{ openvpn_windows64_installer_url }}"
  - "{{ openvpn_windows64_installer_sig_url }}"

# OS X
tunnelblick_version: "3.7.0"
tunnelblick_build: "4790"
tunnelblick_filename: "Tunnelblick_{{ tunnelblick_version }}_build_{{ tunnelblick_build }}.dmg"
tunnelblick_href: "{{ openvpn_mirror_href_base }}/{{ tunnelblick_filename }}"
tunnelblick_url: "https://tunnelblick.net/release/{{ tunnelblick_filename }}"
tunnelblick_checksum: "sha256:5053038aa8caf7dea66dcab11d6d240672216e6546eff4c2622e216c61af85e5"
