---
# OpenConnect Download variables
# ------------------------------
openconnect_mirror_location: "{{ streisand_mirror_location }}/openconnect"
openconnect_mirror_href_base: "/mirror/openconnect"

# Source
openconnect_source_version: "7.06"
openconnect_source_filename: "openconnect-{{ openconnect_source_version }}.tar.gz"
openconnect_source_href: "{{ openconnect_mirror_href_base }}/{{ openconnect_source_filename }}"
# This CDN mirrors the OpenConnect source code, and helps mitigate
# connection errors that were occurring when using the project's
# official download location.
openconnect_source_url: "https://d1shxn4vnb0yj3.cloudfront.net/{{ openconnect_source_filename }}"
openconnect_source_checksum: "sha256:facf695368dc4537a6a30e2147be90b1d77ee3cb2d269eaef070b6d9ddab70f2"

# Windows
openconnect_windows_version: "v1.5.1"
openconnect_windows_filename: "openconnect-gui-1.5.1-win32.exe"
openconnect_windows_href: "{{ openconnect_mirror_href_base }}/{{ openconnect_windows_filename }}"
openconnect_windows_url: "https://github.com/openconnect/openconnect-gui/releases/download/{{ openconnect_windows_version }}/{{ openconnect_windows_filename }}"
openconnect_windows_checksum: "sha256:65ea336108640b44eb16192c7d357953895ce9f61f5ee77d124e56e98714cc7e"

# The below section is commented out as v1.5.1 OpenConnect GUI for macOS crashes on El Capitan when
# attempting to connect.
# see issue: https://github.com/openconnect/openconnect-gui/issues/160
# macOS
#openconnect_macos_version: "v1.5.1"
#openconnect_macos_filename: "openconnect-gui-1.5.1-Darwin.dmg"
#openconnect_macos_href: "{{ openconnect_mirror_href_base }}/{{ openconnect_macos_filename }}"
#openconnect_macos_url: "https://github.com/openconnect/openconnect-gui/releases/download/{{ openconnect_macos_version }}/{{ openconnect_macos_filename }}"
#openconnect_macos_checksum: "sha256:b2c338cfe9d0725bee98893225449e27cf7e337d43b0f8b08aec96de6f761f08"

openconnect_download_urls:
  - { url: "{{ openconnect_source_url }}",  checksum: "{{ openconnect_source_checksum }}" }
  - { url: "{{ openconnect_windows_url }}", checksum: "{{ openconnect_windows_checksum }}" }
  #- { url: "{{ openconnect_macos_url }}", checksum: "{{ openconnect_macos_checksum }}" }
