---
# Shadowsocks Download variables
# ------------------------------
shadowsocks_mirror_location: "{{ streisand_mirror_location }}/shadowsocks"
shadowsocks_mirror_href_base: "/mirror/shadowsocks"

# Android
shadowsocks_android_version: "2.10.7"
shadowsocks_android_filename: "shadowsocks-nightly-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_android_filename }}"
shadowsocks_android_url: "https://github.com/shadowsocks/shadowsocks-android/releases/download/v{{ shadowsocks_android_version }}/shadowsocks-nightly-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_checksum: "sha256:35387a83cf56629972d679d483efb2f9a14c69bc794a2b89f7763adc6904f2a4"

# Windows
shadowsocks_gui_version: "3.0"
shadowsocks_gui_filename: "Shadowsocks-{{ shadowsocks_gui_version }}.zip"
shadowsocks_gui_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_url: "https://github.com/shadowsocks/shadowsocks-windows/releases/download/{{ shadowsocks_gui_version }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_checksum: "sha256:aa1689d0e4fe83becafdaae7862fa3bd0335229f80cf55d00d4c12bcb1d65fe8"

# OS X
shadowsocks_x_ng_version: "1.2"
shadowsocks_x_ng_filename: "ShadowsocksX-NG-{{ shadowsocks_x_ng_version }}.dmg"
shadowsocks_x_ng_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_x_ng_filename }}"
shadowsocks_x_ng_url: "https://github.com/shadowsocks/ShadowsocksX-NG/releases/download/{{ shadowsocks_x_ng_version }}/{{ shadowsocks_x_ng_filename }}"
shadowsocks_x_ng_checksum: "sha256:c9565a8af063c73bf3fc112f6501fe08931c63631d51910c33372db736ec5c45"

# Linux
shadowsocks_python_version: "2.8.2"
shadowsocks_python_filename: "shadowsocks-{{ shadowsocks_python_version }}.tar.gz"
shadowsocks_python_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_python_filename }}"
shadowsocks_python_url: "https://pypi.python.org/packages/source/s/shadowsocks/{{ shadowsocks_python_filename }}"
shadowsocks_python_checksum: "sha256:52800de519783009f12c5634c1d69a43626a1e0a1a1c25725b2d8aa31b767377"

shadowsocks_download_urls:
  - { url: "{{ shadowsocks_android_url }}", checksum: "{{ shadowsocks_android_checksum }}" }
  - { url: "{{ shadowsocks_gui_url }}",     checksum: "{{ shadowsocks_gui_checksum }}" }
  - { url: "{{ shadowsocks_x_ng_url }}",    checksum: "{{ shadowsocks_x_ng_checksum }}" }
  - { url: "{{ shadowsocks_python_url }}",  checksum: "{{ shadowsocks_python_checksum }}" }
