---
# SSH Client Download variables
# -----------------------------
ssh_mirror_location: "{{ streisand_mirror_location }}/ssh"
ssh_mirror_href_base: "/mirror/ssh"

putty_key_id: "0x9DFE2648B43434E4"
putty_expected_fingerprint: "Key fingerprint = 0054 DDAA 8ADA 15D2 768A  6DE7 9DFE 2648 B434 34E4"

putty_base_download_url: "http://the.earth.li/~sgtatham/putty/latest/x86"

putty_filename: "putty.exe"
putty_sig_filename: "{{ putty_filename }}.gpg"
putty_href: "{{ ssh_mirror_href_base }}/{{ putty_filename }}"
# download-and-verify.yml renames files with non-standard extensions
putty_sig_href: "{{ ssh_mirror_href_base }}/{{ putty_filename }}.asc"
putty_url: "{{ putty_base_download_url }}/{{ putty_filename }}"
putty_sig_url: "{{ putty_base_download_url }}/{{ putty_sig_filename }}"

putty_download_urls:
  - "{{ putty_url }}"
  - "{{ putty_sig_url }}"

sshuttle_version: "0.78.0"
sshuttle_filename: "sshuttle-{{ sshuttle_version }}.tar.gz"
sshuttle_href: "{{ ssh_mirror_href_base }}/{{ sshuttle_filename }}"
sshuttle_url: "https://codeload.github.com/sshuttle/sshuttle/tar.gz/v{{ sshuttle_version }}"
sshuttle_checksum: "sha256:0742e3e670c8df629ae702a32cfad96c7c4e8f7ab8f66c26d94c55d42b01e4b4"
