---
# Tor Download variables
# ----------------------
tor_mirror_location: "{{ streisand_mirror_location }}/tor"
tor_mirror_href_base: "/mirror/tor"

tor_browser_developers_key_id: "0x4E2C6E8793298290"
tor_browser_developers_expected_fingerprint: "Key fingerprint = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290"

tor_base_download_url: "https://dist.torproject.org/torbrowser"

# Windows
tor_browser_bundle_windows_filename: "torbrowser-install-{{ tor_browser_bundle_version }}_en-US.exe"
tor_browser_bundle_windows_sig_filename: "{{ tor_browser_bundle_windows_filename }}.asc"
tor_browser_bundle_windows_href: "{{ tor_mirror_href_base }}/{{ tor_browser_bundle_windows_filename }}"
tor_browser_bundle_windows_sig_href: "{{ tor_mirror_href_base }}/{{ tor_browser_bundle_windows_sig_filename }}"
tor_browser_bundle_windows_url: "{{ tor_base_download_url }}/{{ tor_browser_bundle_version }}/{{ tor_browser_bundle_windows_filename }}"
tor_browser_bundle_windows_sig_url: "{{ tor_base_download_url }}/{{ tor_browser_bundle_version }}/{{ tor_browser_bundle_windows_sig_filename }}"

# OS X
tor_browser_bundle_osx_filename: "TorBrowser-{{ tor_browser_bundle_version }}-osx64_en-US.dmg"
tor_browser_bundle_osx_sig_filename: "{{ tor_browser_bundle_osx_filename }}.asc"
tor_browser_bundle_osx_href: "{{ tor_mirror_href_base }}/{{ tor_browser_bundle_osx_filename }}"
tor_browser_bundle_osx_sig_href: "{{ tor_mirror_href_base }}/{{ tor_browser_bundle_osx_sig_filename }}"
tor_browser_bundle_osx_url: "{{ tor_base_download_url }}/{{ tor_browser_bundle_version }}/{{ tor_browser_bundle_osx_filename }}"
tor_browser_bundle_osx_sig_url: "{{ tor_base_download_url }}/{{ tor_browser_bundle_version }}/{{ tor_browser_bundle_osx_sig_filename }}"

# Linux
tor_browser_bundle_linux32_filename: "tor-browser-linux32-{{ tor_browser_bundle_version }}_en-US.tar.xz"
tor_browser_bundle_linux32_sig_filename: "{{ tor_browser_bundle_linux32_filename }}.asc"
tor_browser_bundle_linux32_href: "{{ tor_mirror_href_base }}/{{ tor_browser_bundle_linux32_filename }}"
tor_browser_bundle_linux32_sig_href: "{{ tor_mirror_href_base }}/{{ tor_browser_bundle_linux32_sig_filename }}"
tor_browser_bundle_linux32_url: "{{ tor_base_download_url }}/{{ tor_browser_bundle_version }}/{{ tor_browser_bundle_linux32_filename }}"
tor_browser_bundle_linux32_sig_url: "{{ tor_base_download_url }}/{{ tor_browser_bundle_version }}/{{ tor_browser_bundle_linux32_sig_filename }}"

tor_browser_bundle_linux64_filename: "tor-browser-linux64-{{ tor_browser_bundle_version }}_en-US.tar.xz"
tor_browser_bundle_linux64_sig_filename: "{{ tor_browser_bundle_linux64_filename }}.asc"
tor_browser_bundle_linux64_href: "{{ tor_mirror_href_base }}/{{ tor_browser_bundle_linux64_filename }}"
tor_browser_bundle_linux64_sig_href: "{{ tor_mirror_href_base }}/{{ tor_browser_bundle_linux64_sig_filename }}"
tor_browser_bundle_linux64_url: "{{ tor_base_download_url }}/{{ tor_browser_bundle_version }}/{{ tor_browser_bundle_linux64_filename }}"
tor_browser_bundle_linux64_sig_url: "{{ tor_base_download_url }}/{{ tor_browser_bundle_version }}/{{ tor_browser_bundle_linux64_sig_filename }}"

tor_download_urls:
  - "{{ tor_browser_bundle_windows_url }}"
  - "{{ tor_browser_bundle_windows_sig_url }}"
  - "{{ tor_browser_bundle_osx_url }}"
  - "{{ tor_browser_bundle_osx_sig_url }}"
  - "{{ tor_browser_bundle_linux32_url }}"
  - "{{ tor_browser_bundle_linux32_sig_url }}"
  - "{{ tor_browser_bundle_linux64_url }}"
  - "{{ tor_browser_bundle_linux64_sig_url }}"
