---
- name: Provision the Linode Server
# =================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    regions:
      "1": 4
      "2": 2
      "3": 10
      "4": 3
      "5": 7
      "6": 6
      "7": 9
      "8": 8
      "9": 11

  vars_prompt:
    - name: "linode_datacenter"
      prompt: >
        What region should the server be located in?
          1. Atlanta
          2. Dallas
          3. Frankfurt
          4. Fremont
          5. London
          6. Newark
          7. Singapore
          8. Tokyo
          9. Tokyo 2
        Please choose the number of your region. Press enter for default (#7) region.
      default: "7"
      private: no

    - name: "linode_server_name"
      prompt: "\nWhat should the server be named? Press enter for default (streisand).\n"
      default: "streisand"
      private: no

    - name: "linode_api_key"
      prompt: "\n\nThe following information can be found in the Linode Manager.\nhttps://manager.linode.com/profile/api\n\nWhat is your Linode API key?\n"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...\n"

  roles:
    - genesis-linode


- include: streisand.yml
